# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.2.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _wordstore
else:
    import _wordstore

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _wordstore.delete_SwigPyIterator

    def value(self):
        return _wordstore.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _wordstore.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _wordstore.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _wordstore.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _wordstore.SwigPyIterator_equal(self, x)

    def copy(self):
        return _wordstore.SwigPyIterator_copy(self)

    def next(self):
        return _wordstore.SwigPyIterator_next(self)

    def __next__(self):
        return _wordstore.SwigPyIterator___next__(self)

    def previous(self):
        return _wordstore.SwigPyIterator_previous(self)

    def advance(self, n):
        return _wordstore.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _wordstore.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _wordstore.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _wordstore.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _wordstore.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _wordstore.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _wordstore.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _wordstore:
_wordstore.SwigPyIterator_swigregister(SwigPyIterator)
class StringVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _wordstore.StringVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _wordstore.StringVector___nonzero__(self)

    def __bool__(self):
        return _wordstore.StringVector___bool__(self)

    def __len__(self):
        return _wordstore.StringVector___len__(self)

    def __getslice__(self, i, j):
        return _wordstore.StringVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _wordstore.StringVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _wordstore.StringVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _wordstore.StringVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _wordstore.StringVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _wordstore.StringVector___setitem__(self, *args)

    def pop(self):
        return _wordstore.StringVector_pop(self)

    def append(self, x):
        return _wordstore.StringVector_append(self, x)

    def empty(self):
        return _wordstore.StringVector_empty(self)

    def size(self):
        return _wordstore.StringVector_size(self)

    def swap(self, v):
        return _wordstore.StringVector_swap(self, v)

    def begin(self):
        return _wordstore.StringVector_begin(self)

    def end(self):
        return _wordstore.StringVector_end(self)

    def rbegin(self):
        return _wordstore.StringVector_rbegin(self)

    def rend(self):
        return _wordstore.StringVector_rend(self)

    def clear(self):
        return _wordstore.StringVector_clear(self)

    def get_allocator(self):
        return _wordstore.StringVector_get_allocator(self)

    def pop_back(self):
        return _wordstore.StringVector_pop_back(self)

    def erase(self, *args):
        return _wordstore.StringVector_erase(self, *args)

    def __init__(self, *args):
        _wordstore.StringVector_swiginit(self, _wordstore.new_StringVector(*args))

    def push_back(self, x):
        return _wordstore.StringVector_push_back(self, x)

    def front(self):
        return _wordstore.StringVector_front(self)

    def back(self):
        return _wordstore.StringVector_back(self)

    def assign(self, n, x):
        return _wordstore.StringVector_assign(self, n, x)

    def resize(self, *args):
        return _wordstore.StringVector_resize(self, *args)

    def insert(self, *args):
        return _wordstore.StringVector_insert(self, *args)

    def reserve(self, n):
        return _wordstore.StringVector_reserve(self, n)

    def capacity(self):
        return _wordstore.StringVector_capacity(self)
    __swig_destroy__ = _wordstore.delete_StringVector

# Register StringVector in _wordstore:
_wordstore.StringVector_swigregister(StringVector)
class WordStore(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def add(self, word):
        return _wordstore.WordStore_add(self, word)

    def count(self):
        return _wordstore.WordStore_count(self)

    def join(self, sep):
        return _wordstore.WordStore_join(self, sep)

    def words(self):
        return _wordstore.WordStore_words(self)

    def words_ref(self):
        return _wordstore.WordStore_words_ref(self)

    def __init__(self):
        _wordstore.WordStore_swiginit(self, _wordstore.new_WordStore())
    __swig_destroy__ = _wordstore.delete_WordStore

# Register WordStore in _wordstore:
_wordstore.WordStore_swigregister(WordStore)

def total_length(items):
    return _wordstore.total_length(items)

